apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mariadb/service.yaml
  - mariadb/statefulset.yaml
  - mariadb/sealedsecret.yaml
  - wordpress/pvc.yaml
  - wordpress/deployment.yaml
  - wordpress/service.yaml
  - wordpress/sealedsecret.yaml
  - namespace.yaml
  - ingress.yaml
