apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-expose
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Terorinsh/agro-gops.git
    targetRevision: main
    path: manifests/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true